In [1]:
import pandas as pd
import numpy as np

In [21]:
#1.1
gift = pd.read_csv('ForeignGifts_edu.csv')
gift

,ID,OPEID,Institution Name,City,State,Foreign Gift Received Date,Foreign Gift Amount,Gift Type,Country of Giftor,Giftor Name
0,1,102000,Jacksonville State University,Jacksonville,AL,43738,250000,Monetary Gift,CHINA,NaN
1,2,104700,Troy University,Troy,AL,43592,463657,Contract,CHINA,Confucius Institute Headquarters
2,3,105100,University of Alabama,Tuscaloosa,AL,43466,3649107,Contract,ENGLAND,Springer Nature Customer Service Ce
3,4,105100,University of Alabama,Tuscaloosa,AL,43472,1000,Contract,SAUDI ARABIA,Saudi Arabia Education Mission
4,5,105100,University of Alabama,Tuscaloosa,AL,43479,49476,Contract,SAUDI ARABIA,Saudi Arabia Education Mission
...,...,...,...,...,...,...,...,...,...,...
28216,28217,4279700,Albert Einstein College of Medicine,Bronx,NY,42704,381717,Contract,CHINA,Chia Tai TianQing Pharmaceutical Gr
28217,28218,4279700,Albert Einstein College of Medicine,Bronx,NY,42778,444938,Contract,ISRAEL,BL Oncology Ltd
28218,28219,4279700,Albert Einstein College of Medicine,Bronx,NY,42907,1064580,Contract,ENGLAND,Roche Products Limited
28219,28220,4279700,Albert Einstein College of Medicine,Bronx,NY,42948,737375,Contract,SWITZERLAND,F Hoffman-La Roche Ltd
28220,28221,4279700,Albert Einstein College of Medicine,Bronx,NY,43692,1024469,Monetary Gift,ISRAEL,Estate of Alfred Gertrud Sommerguth

In [22]:
#1.2
gift['Gift Type'].unique()

array(['Monetary Gift', 'Contract', 'Real Estate'], dtype=object)

#### It looks like there are 3 types of gifts: Monetary, Contract, and Real Estate

In [29]:
#1.3.1
gift.groupby('Country of Giftor')['Foreign Gift Amount'].sum().sort_values(ascending=False)

Country of Giftor
QATAR           2706240869
ENGLAND         1464906771
CHINA           1237952112
SAUDI ARABIA    1065205930
BERMUDA          899593972
                   ...
IRAN                    80
ST. LUCIA               50
CROATIA                 26
SLOVAKIA                20
ERITREA                  3
Name: Foreign Gift Amount, Length: 155, dtype: int64

In [30]:
#1.3.2
gift['Country of Giftor'].value_counts()

Country of Giftor
ENGLAND                  3655
CHINA                    2461
CANADA                   2344
JAPAN                    1896
SWITZERLAND              1676
                         ...
NEPAL                       1
ST. KITTS-NEVIS             1
TUNISIA                     1
MARSHAL ISLANDS (THE)       1
ANTIGUA                     1
Name: count, Length: 155, dtype: int64

In [35]:
#1.3.1
gift.groupby('Country of Giftor')['Foreign Gift Amount'].mean().sort_values(ascending=False)

Country of Giftor
BERMUDA      7.688837e+06
ECUADOR      3.985140e+06
QATAR        3.905109e+06
ANTIGUA      3.435545e+06
JERSEY       3.064589e+06
                 ...
ST. LUCIA    5.000000e+01
IRAN         4.000000e+01
CROATIA      2.600000e+01
SLOVAKIA     2.000000e+01
ERITREA      3.000000e+00
Name: Foreign Gift Amount, Length: 155, dtype: float64

In [36]:
#1.3.4
gift.groupby('Institution Name')['Foreign Gift Amount'].sum().sort_values(ascending=False)

Institution Name
Carnegie Mellon University               1477922504
Cornell University                       1289937761
Harvard University                        954803610
Massachusetts Institute of Technology     859071692
Yale University                           613441311
                                            ...
Jacksonville State University                250000
Metropolitan State University                235439
University of California, Merced             182514
University of Central Oklahoma               160288
University of Jamestown                         500
Name: Foreign Gift Amount, Length: 318, dtype: int64

In [37]:
#1.3.5
gift['Institution Name'].value_counts()

Institution Name
University of California, Los Angeles          3916
California Institute of Technology             2502
Columbia University in the City of New York    1127
Ohio State University (The)                    1014
Johns Hopkins University                        899
                                               ...
Westmont College                                  1
Des Moines Area Community College                 1
Beth Medrash Govoha of America                    1
Columbia Southern University                      1
Presidio Graduate School                          1
Name: count, Length: 318, dtype: int64

In [40]:
#1.3.6
uni_totals = gift.groupby('Institution Name')['Foreign Gift Amount'].sum()

mean_total_per_uni = uni_totals.mean()
median_total_per_uni = uni_totals.median()

print(f"Mean donation total by Uni: {mean_total_per_uni:,.2f}")
print(f"Median donation total by Uni: {median_total_per_uni:,.2f}")

Mean donation total by Uni: 52,202,878.97
Median donation total by Uni: 6,486,791.50

#### The difference between the mean and median donations to universities is due to the distribution being skewed heavily by uncommon, large donations. This pulls the mean amount higher much faster than it does the median amount.

In [41]:
#1.3.7
gift.groupby(['Country of Giftor', 'Institution Name'])['Foreign Gift Amount'].sum().reset_index().sort_values('Foreign Gift Amount', ascending=False)

,Country of Giftor,Institution Name,Foreign Gift Amount
1865,QATAR,Cornell University,1018473315
159,BERMUDA,Carnegie Mellon University,750000000
1884,QATAR,Texas A&M University,504099350
1864,QATAR,Carnegie Mellon University,425410702
1872,QATAR,Georgetown University,327128310
...,...,...,...
370,CAYMAN ISLANDS (THE),Johns Hopkins University,10
2552,TRINIDAD,Westminster Theological Seminary,10
990,GERMANY,Westminster Theological Seminary,10
788,ERITREA,"University of California, Los Angeles",3
1672,MEXICO,"University of California, Merced",1

In [42]:
#1.3.8
gift.groupby('Giftor Name')['Foreign Gift Amount'].agg(Total_Amount='sum', Gift_Count='count').sort_values('Total_Amount', ascending=False).head(10)

                                     Total_Amount  Gift_Count
Giftor Name
Qatar Foundation                       1166503744         261
Qatar Foundation/Qatar National Res     796197000          10
Qatar Foundation for Education          373945215           6
Anonymous                               338793629         262
Saudi Arabian Cultural Mission          275221475         480
HCL                                     190000000           5
Church of Jesus Christ of LDS           185203715           7
Emirates Institute for Advanced Sc      170641244          24
QIC                                     148355497           2
Anonymous #9                             96334996           4